### ISSUE TITLE
Anthropic API key does not work

### ISSUE THREAD

**Issue by mk1123** [intellibar/main#49]
Hi, 

I'm trying to test out Intelilibar's Claude integration, but every time I try to use it, I see this "error" response:

```
400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between &quot;user&quot; and &quot;assistant&quot;, but found multiple &quot;user&quot; roles in a row"}}
```

**Comment by astoilkov** [comment]
I fixed this. The next release will include it. Thanks for reporting!

**Comment by erusev** [comment]
This should be fixed in the [latest release](https://github.com/intellibar/main/releases/tag/0.31.0).
