### ISSUE TITLE
Enable Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by 5183nischal** [intellibar/main#50]
Claude 3.5 sonnet was just released and has impressive performance improvements with better latency and cheaper price. Would be great to access this. I'm guessing selecting soonet in setting currently doesn't point to this? Is there a way to point to 3.5 ourselves or should we wait for new releas?

Thank you!

**Comment by erusev** [comment]
We're on it 👨‍💻

**Comment by erusev** [comment]
> I'm guessing selecting soonet in setting currently doesn't point to this? Is there a way to point to 3.5 ourselves or should we wait for new releas?

Yes, right the app points to the Claude 3 Sonnet model, but we'll try to release an update later today that add support for Claude 3.5 Sonnet

**Comment by erusev** [comment]
This is now fixed in [0.31](https://github.com/intellibar/main/releases/tag/0.31.0).
