### ISSUE TITLE
Render/display issue with pinned window

### ISSUE THREAD

**Issue by ggerganov** [intellibar/main#51]
On M1 Pro, Sonoma 14.4.1, Intellibar v0.30.0, pinned windows do not render properly when losing focus:

https://github.com/intellibar/main/assets/1991296/f0406a9e-9efc-4ba8-8765-bac1ed6023f3

I think this worked with v0.29.0

**Comment by erusev** [comment]
Thanks! We're on it 👨‍💻

In the meantime, you can use light mode as a workaround as this seem to only affect dark mode.

**Comment by erusev** [comment]
This is now fixed in [0.31](https://github.com/intellibar/main/releases/tag/0.31.0).
