### ISSUE TITLE
Non-breking space when copy-paste manually

### ISSUE THREAD

**Issue by cvladan** [intellibar/main#53]
When I select result text using my mouse, spaces are not spaces, but "invisible non-whitespace space" characters, but when I click on the "copy to clipboard" icon, then everything is as expected.

Model is LLama3 from Groq, but I think it is in all models.

**Comment by astoilkov** [comment]
I can't seem to replicate this.

What version of IntelliBar are you running? Any ideas on what I might be missing?

**Comment by cvladan** [comment]
Now I also can't replicate that. I don't understand. I will close this ticket and I'll see later if it happens again. I think maybe there's something else going on anyway.

**Comment by cvladan** [comment]
I replicated it now, again. This happens for sure when pasting into an **Asana** task or comment. Maybe it's similar with some other browser apps, but Asana for sure.

**Comment by astoilkov** [comment]
Hmm, tried with Asana as well but still doesn't happen. Here's a GIF of what I'm doing. Am I missing something?
![CleanShot 2024-07-23 at 10 05 03](https://github.com/user-attachments/assets/c7db6cb0-b4fd-4bda-96c3-72ac1e2c3f39)

Also, can you test if the issue still happens if you go back and then forward (you can use the buttons in the titlebar)?

**Comment by cvladan** [comment]
Replicating a bug in video


https://github.com/user-attachments/assets/2da6ca7e-c23e-4962-8926-69f7dbd79544

**Comment by cvladan** [comment]
It seems to me that you have properly tried to replicate the bug - but it doesn't happen on your system? I don't understand why? Maybe because I'm using Firefox? I'm not using any clipboard manager or nothing similar.

**Comment by astoilkov** [comment]
I think I replicated the bug and fixed it. Thanks for the video — it helped! The next release will include the fix.

**Comment by cvladan** [comment]
Yes! Thanks!
