### ISSUE TITLE
small floating window

### ISSUE THREAD

**Issue by dmd** [intellibar/main#60]
I'd love the option for a small floating window, rather than sidebar, similar to what the openai chatgpt app provides with its hotkey.

**Comment by dmd** [comment]
#37 related.

**Comment by dmd** [comment]
It helps but I'd love it if it could be optionally just a small window. 

<img width="710" alt="image" src="https://github.com/user-attachments/assets/b80c4d7d-7a7a-42b7-832c-4c735e17a2b4">

Basically my use case here is I love the chatgpt interface, but I don't want to pay $20/month when using it via API is 1/4 that.

**Comment by erusev** [comment]
Thanks! One more question:

Doesn't it feel constraining when the chat is longer, for example because the response is longer or because you have follow-ups?

**Comment by dmd** [comment]
If you are hovering the mouse over the window, you see:

<img width="454" alt="image" src="https://github.com/user-attachments/assets/be4d2d17-a499-434e-964b-20a778d7c9c5">

That second-from-right icon at top right enlarges the window to the 'main' one.

You should play with it - it's extremely well designed.

**Comment by erusev** [comment]
Got it! Thanks, we'll look into it.

**Comment by dmd** [comment]
I start with the small window quite a lot when i'm asking a real quick "how do i do something in the shell". Almost always the answer will be a couple of lines at most. I realize some shells (iterm2, Warp) have this kind of thing built in now, but I don't want AI within 500 miles of my actual shell window (and I want to be able to continue the chat).

**Comment by erusev** [comment]
Do you think the main benefit of the small window that it's floating or that it's small?

**Comment by dmd** [comment]
Hmm. It's a combination of both - it doesn't take up a huge amount of the screen AND it's floating.

**Comment by erusev** [comment]
> Hmm. It's a combination of both - it doesn't take up a huge amount of the screen AND it's floating.

I guess I wonder how much of the problem would go away if we introduced an option that makes the ww "floating" by default.

Do you think an option like that would help?

**Comment by dmd** [comment]
I think the problem for me is still that the window can only be in one of two places - taking up a quarter of my screen on the right, or on the left. 
But it would certainly help some.

**Comment by erusev** [comment]
We just release `038` with an option to `keep on top` in Settings → Labs. The window is now also a bit inset, which also makes it a bit smaller. We are considering another option that controls window size.

**Comment by dmd** [comment]
I'm pretty happy with the way things are now.

**Comment by erusev** [comment]
Great to hear 😊
