### ISSUE TITLE
Delete old chats?

### ISSUE THREAD

**Issue by dmd** [intellibar/main#61]
It seems to keep old chats around forever. Is it possible to delete them?

**Comment by dmd** [comment]
Ah, I found it.

**Comment by erusev** [comment]
In case anyone else is wondering, you can do that from the Command Palette / ⌘P:

> <img width="280.5" alt="CleanShot 2024-09-30 at 20 49 09@2x" src="https://github.com/user-attachments/assets/1baefa08-ea2b-44a5-8a9c-26e5e8fd620b">

**Comment by dmd** [comment]
What's the difference between ⌘P and ⌘K if any?

**Comment by erusev** [comment]
There's none, ⌘K is an alias to ⌘P.
