### ISSUE TITLE
Requiring OpenAI key despite the fact that it's not on.

### ISSUE THREAD

**Issue by KirkPX** [intellibar/main#62]
Getting this error. I only want to use Llama

_The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' })._

**Comment by astoilkov** [comment]
We fixed this. The next release will include the fix. Thanks for reporting!

**Comment by erusev** [comment]
We just released a patch (0.38.2) with a fix for this.
