### ISSUE TITLE
text keeps getting replaced with 'connection error'

### ISSUE THREAD

**Issue by dmd** [intellibar/main#67]
Using Claude, I'll ask a question, it'll start generating text, and then after about a paragraph of response has been written, that paragraph will DISAPPEAR and be replaced with 'connection error'.

**Comment by dmd** [comment]
Note that I'm not getting this from any other client, including simonw/llm and LibreChat, from the same computer.

**Comment by erusev** [comment]
Thanks, we'll look into it.
