### ISSUE TITLE
accessibility access link does nothing

### ISSUE THREAD

**Issue by dmd** [intellibar/main#68]
<img width="565" alt="image" src="https://github.com/user-attachments/assets/ade2b084-d9da-4da3-8951-769372f4091b">

Clicking on the "accessibility access" link has no effect for me (MacOS 15.0.1)

**Comment by astoilkov** [comment]
That's weird. Do you want to help us figure out this together?

Can you try to:
 1. Go to System Settings → Privacy & Security → Accessibility.
 2. Is IntelliBar there? If yes, select IntelliBar.
 3. Click on the minus button on the bottom.
 4. Retry granting IntelliBar accessibility permissions.

If this doesn't work, can you let me know:
 • What version of IntelliBar (arm or intel) you are running?
 • Did you install IntelliBar in the Applications folder, or are you running it inside the DMG, or in a different folder on your computer? Can you try the Applications folder?

Thanks!

**Comment by dmd** [comment]
Oh, I think I know what's happening. 99% chance this is our corporate CrowdStrike FalconSensor being a #$%&.
