### ISSUE TITLE
/commands should only be at start of line

### ISSUE THREAD

**Issue by dmd** [intellibar/main#72]
If I type:

> duck and/or goose

the slash-commands popup shouldn't come up when i hit slash, and slash commands in general probably shouldn't be valid except on their own, at the start of a line.

**Comment by erusev** [comment]
Thanks, we'll look into it.

**Comment by erusev** [comment]
Just release a patch (`0.40.1`) that should fix this. You can still open the slash menu mid-prompt, but it needs to be after a `space` char. Typing `b/w` or anything like that won't trigger it.
