### ISSUE TITLE
Please allow for the modificationon of the shortcurs

### ISSUE THREAD

**Issue by jakob-haywood** [intellibar/main#73]

**Comment by erusev** [comment]
Is there any shortcuts in particular you would like to modify?

**Comment by jakob-haywood** [comment]
Yes, I would like to modify, in particular, the settings: Dock left and Dock right. This is due to their having the most impact on usability, since you can't resize or move the window. For those of us on smaller screens (such as an Amazon Fire 13"), it can be quite annoying to deal with. Although, to be honest, if possible, making all of them customizable is the right way to go.

**Comment by erusev** [comment]
Did you know that you can swipe to dock it to the other side?

**Comment by erusev** [comment]
> those of us on smaller screens (such as an Amazon Fire 13")

You're running macOS on Amazon Fire 13?
