### ISSUE TITLE
"Low cost model" setting keeps resetting

### ISSUE THREAD

**Issue by aabuhijleh** [intellibar/main#75]
Version 0.40.1

https://github.com/user-attachments/assets/9470aef6-d809-4da0-b446-4c2318142926

Maybe changing this setting here in the chat conflicts with it? I'm not sure.

<img width="551" alt="image" src="https://github.com/user-attachments/assets/2d2f9ead-2af2-45ee-be72-ef5a7aa102cc">

**Comment by astoilkov** [comment]
I fixed this. The next release later this week will include the fix.

Thanks for reporting!
