### ISSUE TITLE
Activated license indication

### ISSUE THREAD

**Issue by aabuhijleh** [intellibar/main#76]
Hey guys,

This is a cool product and I've bought a license to support development. If license is activated, maybe there should be an indicator in the app, like in the settings or this command should be removed:

<img width="562" alt="image" src="https://github.com/user-attachments/assets/9fe72f74-f5bc-4aa4-b623-a4a260e4a43e">

**Comment by erusev** [comment]
We'll look into it! Thanks for reporting it, and thanks for your support 🙏

**Comment by astoilkov** [comment]
I've made the command go away when the user has an active license. The next release will include the improvement.

Thanks for the idea!

**Comment by dmd** [comment]
I am licensed, but I see "License status Not Licensed" in settings.

**Comment by astoilkov** [comment]
That's probably because you are an older user. Can you try to activate the license again and see if it goes away? Thanks!

**Comment by dmd** [comment]
<img width="244" alt="image" src="https://github.com/user-attachments/assets/6a6d389d-d823-40db-b6b3-e9adaf59272d" />

**Comment by astoilkov** [comment]
Did you go to https://intellibar.app/activate.html to get a new activation email or did you use the email you used last time? Activation emails work only once.

**Comment by dmd** [comment]
Yes, I do that, I get the activation email, I click on it, Intellibar opens, I go to Status, it says Not licensed.
